#!/bin/bash

#jekyll s && git add . && git commit -m %1 && j

# Commit the specified file to jekyll and push it 
/Users/sjohnson/.rvm/gems/ruby-2.3.1@blog/bin/jekyll build --incremental && git add . && git commit -m "$1" && git push origin gh-pages

